apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-service-config
  namespace: stag
  labels:
    app.kubernetes.io/name: billing-service
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: workshop-phase-4
    app.kubernetes.io/managed-by: workshop-platform
data:
  SERVICE_NAME: billing-service
  APP_ENV: stag
  HTTP_PORT: "8080"
  RABBITMQ_HOST: rabbitmq.rabbitmq.svc.cluster.local
  RABBITMQ_PORT: "5672"
  ORDER_SERVICE_URL: http://order-service.stag.svc.cluster.local
