apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: stag
  labels:
    app.kubernetes.io/name: order-service
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: workshop-phase-4
    app.kubernetes.io/managed-by: workshop-platform
data:
  SERVICE_NAME: order-service
  APP_ENV: stag
  HTTP_PORT: "8080"
  RABBITMQ_HOST: rabbitmq.rabbitmq.svc.cluster.local
  RABBITMQ_PORT: "5672"
  BILLING_SERVICE_URL: http://billing-service.stag.svc.cluster.local
  EXECUTION_SERVICE_URL: http://execution-service.stag.svc.cluster.local
