variable "project" {
  description = "Global challenge prefix."
  type        = string
  default     = "workshop"
}

variable "repo" {
  description = "Official repository slug."
  type        = string
  default     = "platform"
}

variable "environment" {
  description = "AWS environment suffix."
  type        = string
  default     = "stag"

  validation {
    condition     = contains(["stag", "prod"], var.environment)
    error_message = "environment must be stag or prod."
  }
}

variable "resource_suffix" {
  description = "Identifier of the main resource generated by this module."
  type        = string
  default     = "cluster"
}
