apiVersion: v1
kind: Service
metadata:
  name: execution-service
  namespace: stag
  labels:
    app.kubernetes.io/name: execution-service
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: workshop-phase-4
    app.kubernetes.io/managed-by: workshop-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: execution-service
    app.kubernetes.io/component: worker
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
