apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: rabbitmq
type: Opaque
stringData:
  RABBITMQ_USER: "REPLACE_ME"
  RABBITMQ_PASS: "REPLACE_ME"
  RABBITMQ_URL: "amqp://REPLACE_ME:REPLACE_ME@rabbitmq.rabbitmq.svc.cluster.local:5672/"
