apiVersion: v1
kind: Namespace
metadata:
  name: stag
  labels:
    app.kubernetes.io/managed-by: workshop-platform
    workshop.fiap.io/environment: stag
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    app.kubernetes.io/managed-by: workshop-platform
    workshop.fiap.io/environment: prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/managed-by: workshop-platform
